; ------------------------------- Author ----------------------------
; maxchow@qq.com
; CocoaDuck
; Chawye Hsu

; -------------------------- Testing Platform -----------------------
; Monitor:         2560 x 1440 (150%), 15.6inch 165Hz, 16:9, Laptop.
; OS:              Windows 11 IoT Enterprise LTSC 2024(24H2).
; Antivirus:       Windows Defender Enabled, Memory integrity
;                  Enabled, Others Enabled.
; Language:        English and Chinese.
; Mactype Version: 2025.6.9.
; System Tray:     Run with elevated privileges, Normal Mode.
; Test Date:       20260409.

; ------------------------ Basic Information ------------------------
[Preview]
Font=Microsoft YaHei UI
[General]
Name=CocoaDuck 3.0.0
Icon=XMac\XMac.ico,0

; ---------------------- Rendering Configuration --------------------
HintingMode=1
AntiAliasMode=4
LcdFilter=2
NormalWeight=16
BoldWeight=2
BolderMode=0
ItalicSlant=0
GammaMode=0
GammaValue=1.4
Contrast=1.0
RenderWeight=1.0
TextTuning=0
TextTuningR=0
TextTuningG=0
TextTuningB=0
Shadow=1,1,60,FFFFFF,35,000000

; ------------------- Font Loading Configuration -------------------
HookChildProcesses=1
FontLoader=0
FontLink=1
UseMapping=0
MaxHeight=0
MaxBitmap=0
FontSubstitutes=1
DirectWrite=1

; --------------------- Cache Configuration -----------------------
LoadOnDemand=1
CacheMaxFaces=256
CacheMaxSizes=40000000
CacheMaxBytes=40000000
EnableKerning=0

; -------------------------- Direct Write -------------------------
[DirectWrite]
RenderingMode=5
GammaValue=1.4
Contrast=1.0
ClearTypeLevel=0.6

; ------------------------- New Features ---------------------------
[Experimental]
ColorFont=1
ArmBreaker=2

; ------------------------ Font Fine-Tuning ------------------------
[Individual]

; ---------------- Font Substitution Configuration -----------------
[FontSubstitutes]
Monospace Latin fonts
Courier=Cascadia Code
Courier New=Cascadia Code
Lucida Console=Cascadia Code
Consolas=Cascadia Code
; Courier=Cascadia Next SC NF
; Courier New=Cascadia Next SC NF
; Lucida Console=Cascadia Next SC NF
; Consolas=Cascadia Next SC NF
; Cascadia Mono=Cascadia Next SC NF
; Cascadia Code=Cascadia Next SC NF

; ----------- Programs Excluded from Font Replacement ----------------
[ExcludeSub]
; Windows Font Viewer
fontview.exe
; Windows Security Alert
rundll32.exe
; Sysinternals Suite
; Autoruns.exe
; Autoruns64.exe
; Autoruns64a.exe
; procexp.exe
; procexp64.exe
; procexp64a.exe
; Procmon.exe
; Procmon64.exe
; Procmon64a.exe
; Microsoft Office
EXCEL.EXE
POWERPNT.EXE
WINWORD.EXE
; Wallpaper Engine
ui32.exe
; WPS Office
wps.exe
; Onlyoffice
editors.exe
; PDF-XChange Editor
PDFXEdit.exe
; Other Programs
Mihomo Party.exe
LosslessScaling.exe
SVPManager.exe
readest.exe
HandBrake.exe
chrome.exe

; ----- Programs not Rendered or Replaced Fonts (DLL Not Loaded) -----
[UnloadDll]
; ClearType Text Tuner
cttune.exe
; Windows Subsystem for Linux (WSL)
wslhost.exe
wsl.exe
; Java
java.exe
javaw.exe
; Cygwin/MSYS2
gpg.exe
pacman.exe
; Process Lasso
ProcessLasso.exe
; Other Programs
MATLAB.exe
